export const CONSTANT={
    COUNT_ACTION:"COUNT_ACTION",
    COUNT_ACTION_SUCCESS:"COUNT_ACTION_SUCCESS",
    GetMoviesAction:"GET_MOVIES_ACTION",
    GetMoviesActionSuccess:"GET_MOVIES_ACTION_SUCCESS"
}